### ISSUE TITLE
Input images don't appear when running on Google Colab and matplotlib

### ISSUE THREAD

**Issue by oishimilk** [Meijo-TasakiLab/AlexNet#2]
Unfortunately, 
```sh
$ AlexNet/alexnet.py -t dataset -v dataset -e dataset --display matplotlib
```
doesn't show the input images.
The code cell says:
```
path/to/imageに写っているのは，コツメカワウソ だと思います．
<Figure size 640x480 with 1 Axes>
正解率は6.4％でした．
```
I tried `%matplotlib inline` but it doesn't work.
Should we run the code in colab notebooks directly?

**Comment by shikishima-TasakiLab** [comment]
To show input images, you should run the code in colab notebooks directly.
(We should make a Google Colab notebook...?)

**Comment by oishimilk** [comment]
OK, I've created the notebook.

**Comment by shikishima-TasakiLab** [comment]
Thanks.
